"""
Snowflake MCP Server Client
Connects to Snowflake-managed MCP server externally via PAT authentication.
Calls Cortex Analyst (text-to-SQL) and auto-executes the generated query.
"""

import requests
import json
import os
import sys

# -- Configuration --
ACCOUNT = "SFSEAPAC-BSURESH"
MCP_URL = f"https://{ACCOUNT}.snowflakecomputing.com/api/v2/databases/ICEBERG_DUCKDB_DEMO/schemas/PUBLIC/mcp-servers/ECOMMERCE_MCP_SERVER"
PAT = os.environ["HORIZON_PAT"]

HEADERS = {
    "Authorization": f"Bearer {PAT}",
    "Content-Type": "application/json",
}


def mcp_request(method, params=None):
    payload = {"jsonrpc": "2.0", "id": 1, "method": method, "params": params or {}}
    response = requests.post(MCP_URL, headers=HEADERS, json=payload, timeout=90)
    response.raise_for_status()
    return response.json()


def list_tools():
    print("\n" + "=" * 60)
    print("DISCOVERING TOOLS ON SNOWFLAKE MCP SERVER")
    print("=" * 60)
    print(f"\nEndpoint: {MCP_URL}\n")

    result = mcp_request("tools/list")
    tools = result.get("result", {}).get("tools", [])

    for i, tool in enumerate(tools, 1):
        print(f"  [{i}] {tool['name']}")
        print(f"      {tool.get('title', '')}")
        print(f"      {tool.get('description', '')[:80]}")
        print()

    return tools


def call_tool(tool_name, arguments):
    print(f"\n{'─' * 60}")
    print(f"CALLING: {tool_name}")
    print(f"{'─' * 60}")
    print("Waiting for response", end="", flush=True)

    result = mcp_request("tools/call", {"name": tool_name, "arguments": arguments})
    print(" ✓\n")

    content = result.get("result", {}).get("content", [])
    is_error = result.get("result", {}).get("isError", False)

    if is_error:
        print("ERROR:")
        for item in content:
            print(f"  {item.get('text', '')}")
        return result

    for item in content:
        text = item.get("text", "")
        try:
            parsed = json.loads(text)
            if isinstance(parsed, list):
                for entry in parsed:
                    if isinstance(entry, dict):
                        if "text" in entry:
                            print(entry["text"])
                        if "statement" in entry:
                            print(f"\n  SQL: {entry['statement'].strip()}")
            elif isinstance(parsed, dict):
                if "result_set" in parsed:
                    print_result_set(parsed["result_set"])
                else:
                    print(json.dumps(parsed, indent=2))
            else:
                print(parsed)
        except (json.JSONDecodeError, TypeError):
            print(text)

    print("─" * 60)
    return result


def extract_sql(result):
    content = result.get("result", {}).get("content", [])
    for item in content:
        try:
            parsed = json.loads(item.get("text", ""))
            if isinstance(parsed, list):
                for entry in parsed:
                    if isinstance(entry, dict) and "statement" in entry:
                        sql = entry["statement"].strip()
                        if "-- Generated by" in sql:
                            sql = sql[:sql.index("-- Generated by")].strip()
                        return sql.rstrip(";")
        except (json.JSONDecodeError, TypeError):
            pass
    return None


def print_result_set(result_set):
    data = result_set.get("data", [])
    metadata = result_set.get("resultSetMetaData", {})
    columns = [col["name"] for col in metadata.get("rowType", [])]

    if columns:
        print(f"\n  {'  |  '.join(columns)}")
        print(f"  {'─' * (len('  |  '.join(columns)))}")
    for row in data:
        print(f"  {'  |  '.join(str(v) for v in row)}")
    print(f"\n  ({len(data)} row{'s' if len(data) != 1 else ''})")


def main():
    print("=" * 60)
    print("  SNOWFLAKE MCP SERVER CLIENT")
    print("  External access to Cortex AI via Model Context Protocol")
    print("=" * 60)

    if not PAT:
        print("\nERROR: Set HORIZON_PAT environment variable.")
        sys.exit(1)

    tools = list_tools()
    if not tools:
        print("No tools found.")
        sys.exit(1)

    tool_names = [t["name"] for t in tools]

    print("\n" + "=" * 60)
    print("INTERACTIVE MODE - Ask questions (type 'quit' to exit)")
    print("=" * 60)

    while True:
        try:
            question = input("\nYou: ").strip()
        except (EOFError, KeyboardInterrupt):
            break

        if not question or question.lower() in ("quit", "exit", "q"):
            break

        if "review" in question.lower() or "feedback" in question.lower():
            call_tool("product-reviews-search", {"query": question, "limit": 5})
        elif "ecommerce-analytics" in tool_names:
            result = call_tool("ecommerce-analytics", {"message": question})
            sql = extract_sql(result)
            if sql:
                print("\n  Executing SQL...")
                call_tool("run-sql", {"sql": sql})
        elif "ecommerce-agent" in tool_names:
            call_tool("ecommerce-agent", {"text": question})

    print("\nDone.")


if __name__ == "__main__":
    main()
